train_parameters:
  train_manifest: "data/train_data.csv"
  valid_manifest: "data/valid_data.csv"
  batch_size: 64
  learning_rate: 1e-4
  num_epochs: 10
  num_classes: 3
  checkpoint_path: "checkpoints"
